beam: 10
retry_beam: 40

features:
  type: "mfcc"
  use_energy: false
  frame_shift: 10

training:
  - monophone:
      num_iterations: 40
      max_gaussians: 1000
      subset: 0
      boost_silence: 1.25

  - triphone:
      num_iterations: 35
      num_leaves: 2000
      max_gaussians: 10000
      cluster_threshold: -1
      subset: 0
      boost_silence: 1.25
      power: 0.25

  - lda:
      num_leaves: 2500
      max_gaussians: 15000
      subset: 0
      num_iterations: 35
      features:
          splice_left_context: 3
          splice_right_context: 3

  - sat:
      num_leaves: 2500
      max_gaussians: 15000
      power: 0.2
      silence_weight: 0.0
      fmllr_update_type: "diag"
      subset: 0
      features:
          lda: true

  - sat:
      num_leaves: 4200
      max_gaussians: 40000
      power: 0.2
      silence_weight: 0.0
      fmllr_update_type: "diag"
      subset: 0
      features:
          lda: true
          fmllr: true

#  - monophone:
#      num_iterations: 40
#      max_gaussians: 1000
#      boost_silence: 1.0
#
#  - triphone:
#      num_iterations: 35
#      num_leaves: 3100
#      max_gaussians: 50000
#      cluster_threshold: 100
#      boost_silence: 1.0
#      power: 0.25
#
#  - sat:
#      num_leaves: 3100
#      max_gaussians: 50000
#      power: 0.2
#      silence_weight: 0.0
#      cluster_threshold: 100
#      fmllr_update_type: "full"